from __future__ import annotations

from types import TracebackType
from typing import Protocol, Self
from uuid import UUID

from notely.core.models import (
    AISuggestion,
    Annotation,
    CurationRequest,
    CuratedSource,
    Document,
    OutboxEvent,
    ReadingSession,
    StudySession,
    StudySessionDocument,
)


class UnitOfWork(Protocol):
    async def __aenter__(self) -> Self: ...

    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...

    async def get_document(self, document_id: UUID) -> Document | None: ...

    async def get_document_by_sha256(self, sha256: str) -> Document | None: ...

    async def list_documents(self) -> list[Document]: ...

    async def add_document(self, document: Document) -> None: ...

    async def add_annotation(self, annotation: Annotation) -> None: ...

    async def get_annotation(self, annotation_id: UUID) -> Annotation | None: ...

    async def add_curation_request(self, request: CurationRequest) -> None: ...

    async def get_curation_request(self, annotation_id: UUID) -> CurationRequest | None: ...

    async def update_curation_request(self, request: CurationRequest) -> None: ...

    async def list_curated_sources(self, request_id: UUID) -> list[CuratedSource]: ...

    async def source_is_current(self, source: CuratedSource, session_id: UUID) -> bool: ...

    async def add_outbox_event(self, event: OutboxEvent) -> None: ...

    async def list_annotations(self, document_id: UUID) -> list[Annotation]: ...

    async def add_reading_session(self, session: ReadingSession) -> None: ...

    async def update_reading_session(self, session: ReadingSession) -> None: ...

    async def get_reading_session(self, session_id: UUID) -> ReadingSession | None: ...

    async def add_study_session(self, session: StudySession) -> None: ...

    async def update_study_session(self, session: StudySession) -> None: ...

    async def get_study_session(self, session_id: UUID) -> StudySession | None: ...

    async def list_study_sessions(self) -> list[StudySession]: ...

    async def add_study_session_document(self, link: StudySessionDocument) -> None: ...

    async def get_study_session_document(
        self, session_id: UUID, document_id: UUID
    ) -> StudySessionDocument | None: ...

    async def list_study_session_documents(
        self, session_id: UUID
    ) -> list[StudySessionDocument]: ...

    async def remove_study_session_document(self, session_id: UUID, document_id: UUID) -> None: ...

    async def next_study_session_position(self, session_id: UUID) -> int: ...

    async def add_ai_suggestion(self, suggestion: AISuggestion) -> None: ...

    async def update_ai_suggestion(self, suggestion: AISuggestion) -> None: ...

    async def get_ai_suggestion(self, suggestion_id: UUID) -> AISuggestion | None: ...

    async def list_ai_suggestions(
        self, subject_type: str, subject_id: UUID
    ) -> list[AISuggestion]: ...

    async def commit(self) -> None: ...
